CREATE TABLE CUSTOMERS 
(
  CUSTOMER_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL 
, CUSTOMER_LAST_NAME VARCHAR2(45) NOT NULL 
, CUSTOMER_FIRST_NAME VARCHAR2(20) NOT NULL 
, CUSTOMER_CITY VARCHAR2(45) 
, CUSTOMER_COUNTRY VARCHAR2(45) 
, CUSTIMER_EMAIL VARCHAR2(45) 
, CONSTRAINT CUSTOMERS_PK PRIMARY KEY 
  (
    CUSTOMER_ID 
  )
  ENABLE 
);

COMMENT ON TABLE CUSTOMERS IS 'The customer entity.';
