CREATE TABLE DISCOUNTS 
(
  DISC_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 NOT NULL 
, DISC_NAME VARCHAR2(45 BYTE) NOT NULL 
, DISC_VALUE NUMBER(19, 4) DEFAULT 0 NOT NULL 
, CONSTRAINT DISCOUNT_PK PRIMARY KEY 
  (
    DISC_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX DISCOUNT_PK ON DISCOUNTS (DISC_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE DISCOUNTS
ADD CONSTRAINT DISCOUNTS_NAME_UK UNIQUE 
(
  DISC_NAME 
)
ENABLE;
