CREATE TABLE OFFERS 
(
  OFFER_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL 
, RENTAL_ID NUMBER NOT NULL 
, DISCOUNT_ID NUMBER 
, CONSTRAINT OFFERS_PK PRIMARY KEY 
  (
    OFFER_ID 
  )
  ENABLE 
);

ALTER TABLE OFFERS
ADD CONSTRAINT OFFERS_DISCOUNTS_FK FOREIGN KEY
(
  DISCOUNT_ID 
)
REFERENCES DISCOUNTS
(
  DISC_ID 
)
ENABLE;

ALTER TABLE OFFERS
ADD CONSTRAINT OFFERS_RENTALS_FK FOREIGN KEY
(
  RENTAL_ID 
)
REFERENCES RENTALS
(
  RENT_ID 
)
ENABLE;

COMMENT ON TABLE OFFERS IS 'This table keep track of all offers for a given rental.';
