CREATE TABLE RENTALS 
(
  RENT_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL 
, CUSTOMER_ID NUMBER NOT NULL 
, ROOM_ID NUMBER NOT NULL 
, RENT_ARRIVAL_DATE DATE NOT NULL 
, RENT_DEPARTURE_DATE DATE NOT NULL 
, RENT_DAY_PRICE NUMBER(19,4) NOT NULL 
, RENT_CHECK_IN NUMBER(1) DEFAULT 0 NOT NULL 
, RENT_CHECK_OUT NUMBER(1) DEFAULT 0 NOT NULL 
, RENT_PAYED NUMBER(1) DEFAULT 0 NOT NULL 
, CONSTRAINT RENTALS_PK PRIMARY KEY 
  (
    RENT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RENTALS_PK ON RENTALS (RENT_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE RENTALS
ADD CONSTRAINT RENTALS_FK1 FOREIGN KEY
(
  CUSTOMER_ID 
)
REFERENCES CUSTOMERS
(
  CUSTOMER_ID 
)
ENABLE;

ALTER TABLE RENTALS
ADD CONSTRAINT RENTALS_FK2 FOREIGN KEY
(
  ROOM_ID 
)
REFERENCES ROOMS
(
  ROOM_ID 
)
ENABLE;

COMMENT ON TABLE RENTALS IS 'Entity for reservation and current state of availeability.';
