CREATE TABLE ROOMS
(
  ROOM_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL
, ROOM_FLOOR NUMBER NOT NULL
, ROOM_NUMBER NUMBER NOT NULL
, ROOM_CAPACITY NUMBER NOT NULL
, ROOM_DESCRIPTION LONG
, ROOM_BASE_PRICE NUMBER(19,4)
, CONSTRAINT ROOMS_PK PRIMARY KEY
  (
    ROOM_ID
  )
  ENABLE
);

COMMENT ON TABLE ROOMS IS 'Representation of room entity.';
