CREATE TABLE SERVICES
(
  SERVICE_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL
, SERVICE_NAME VARCHAR2(45) NOT NULL
, SERVICE_PRICE NUMBER(19,4) NOT NULL
, CONSTRAINT SERVICES_PK PRIMARY KEY
  (
    SERVICE_ID
  )
  ENABLE
);

ALTER TABLE SERVICES
ADD CONSTRAINT SERVICES_NAME_UK UNIQUE
(
  SERVICE_NAME
)
ENABLE;

COMMENT ON TABLE SERVICES IS 'This entity connects the reservation with some extra service.';
