CREATE TABLE TRADES 
(
  TRADE_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL 
, SERVICE_ID NUMBER NOT NULL 
, RENTAL_ID NUMBER NOT NULL 
, TRADE_PAYED NUMBER(1) DEFAULT 0 NOT NULL 
, CONSTRAINT TRADES_PK PRIMARY KEY 
  (
    TRADE_ID 
  )
  ENABLE 
);

ALTER TABLE TRADES
ADD CONSTRAINT TRADES_FK1 FOREIGN KEY
(
  SERVICE_ID 
)
REFERENCES SERVICES
(
  SERVICE_ID 
)
ENABLE;

ALTER TABLE TRADES
ADD CONSTRAINT TRADES_FK2 FOREIGN KEY
(
  RENTAL_ID 
)
REFERENCES RENTALS
(
  RENT_ID 
)
ENABLE;

COMMENT ON TABLE TRADES IS 'This table keep track of all services for a given rental.';
