CREATE TABLE SCHEMA_LOG 
(
  MESSAGE VARCHAR2(256) NOT NULL 
);


CREATE OR REPLACE TRIGGER CREATE_OBJ_LOG BEFORE
CREATE ON C##FRIDMAN.SCHEMA
  DECLARE
    MESSAGE VARCHAR2(100) := 'User '||DICTIONARY_OBJ_OWNER||'created obj witn name = '||DICTIONARY_OBJ_NAME;
  BEGIN
    INSERT INTO Customers_Log VALUES
      (MESSAGE
      );
  END;